version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: orbweaver
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  indexer:
    build:
      context: ./indexer
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=postgres
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - ./indexer:/app
      - /app/node_modules

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - INDEXER_URL=http://indexer:4000
    ports:
      - "4001:4001"
    depends_on:
      - indexer
    volumes:
      - ./gateway:/app
      - /app/node_modules

volumes:
  postgres_data:

