/**
 * Gateway Constants
 * Central configuration constants for the OrbWeaver Gateway
 */

const API_VERSION = 'v1';
const MAX_QUERY_DEPTH = 10;
const DEFAULT_PAGE_SIZE = 20;
const MAX_PAGE_SIZE = 100;
const MIN_PAGE_SIZE = 1;

// Rate limiting
const RATE_LIMIT_WINDOW_MS = 60000; // 1 minute
const RATE_LIMIT_MAX_REQUESTS = 100;
const RATE_LIMIT_MAX_CROSS_CHAIN = 10;

// Caching
const CACHE_TTL_DEFAULT = 3600000; // 1 hour
const CACHE_TTL_SCHEMA = 86400000; // 24 hours
const CACHE_MAX_SIZE = 1000;

// Timeouts
const INDEXER_REQUEST_TIMEOUT = 30000; // 30 seconds
const DEFAULT_QUERY_TIMEOUT = 60000; // 60 seconds

// Supported chains
const SUPPORTED_CHAIN_IDS = [1, 137, 56, 10, 42161, 43114];

// Error codes
const ERROR_CODES = {
  INVALID_QUERY: 'INVALID_QUERY',
  SCHEMA_NOT_FOUND: 'SCHEMA_NOT_FOUND',
  CHAIN_NOT_SUPPORTED: 'CHAIN_NOT_SUPPORTED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  UNAUTHORIZED: 'UNAUTHORIZED'
};

module.exports = {
  API_VERSION,
  MAX_QUERY_DEPTH,
  DEFAULT_PAGE_SIZE,
  MAX_PAGE_SIZE,
  MIN_PAGE_SIZE,
  RATE_LIMIT_WINDOW_MS,
  RATE_LIMIT_MAX_REQUESTS,
  RATE_LIMIT_MAX_CROSS_CHAIN,
  CACHE_TTL_DEFAULT,
  CACHE_TTL_SCHEMA,
  CACHE_MAX_SIZE,
  INDEXER_REQUEST_TIMEOUT,
  DEFAULT_QUERY_TIMEOUT,
  SUPPORTED_CHAIN_IDS,
  ERROR_CODES
};
